#!/usr/bin/env bash
mkdir -p "${HOME}/.config/kitty"
ln -sf "${HOME}/.dotfiles/kitty/kitty.conf" "${HOME}/.config/kitty/kitty.conf"

mkdir -p "${HOME}/.config/kitty/themes"
ln -sf "${HOME}/.dotfiles/kitty/themes/github.conf" "${HOME}/.config/kitty/themes/github.conf"

mkdir -p "${HOME}/.local/bin"
ln -sf "${HOME}/.dotfiles/kitty/kitty-theme" "${HOME}/.local/bin/kitty-theme"
