#!/usr/bin/env bash

read -r -d '' help_message <<EOF
Install basic dotfiles for bash, vim, and git.

usage: install [-fh]

options:
 -f          force create links, overwriting all targets that already exist
 -h, --help  show this help message and exit
EOF

[[ $PWD == ${PWD%/dotfiles} ]] && echo "\
It looks like you aren't in the \`dotfiles\` directory.
Please navigate to \`dotfiles\` and try ./install again."\
&& exit 1

f=''

while :; do
    case $1 in
        -h|--help) echo "$help_message"; exit 0;;
        -f) f='f';;
        *) break
    esac
    shift
done

ln -si"$f" "${PWD}/bash/bash_profile" "${HOME}/.bash_profile"
ln -si"$f" "${PWD}/bash/bashrc" "${HOME}/.bashrc"
ln -si"$f" "${PWD}/bash/inputrc" "${HOME}/.inputrc"

mkdir -p "${HOME}/.vim"
ln -si"$f" "${PWD}/vim/vimrc" "${HOME}/.vim/vimrc"
mkdir -p "${HOME}/.vim/plugin"
ln -si"$f" "${PWD}/vim/sensible.vim" "${HOME}/.vim/plugin/sensible.vim"
mkdir -p "${HOME}/.vim/colors"
ln -si"$f" "${PWD}/vim/base16-default-light.vim" "${HOME}/.vim/colors/base16-default-light.vim"

orig_umask="$(umask)"
umask 0077
mkdir -p "${HOME}/.config"
umask "$orig_umask"

mkdir -p "${HOME}/.config/git"
ln -si"$f" "${PWD}/git/config" "${HOME}/.config/git/config"
ln -si"$f" "${PWD}/git/ignore" "${HOME}/.config/git/ignore"

unset f
unset orig_umask
