#!/bin/bash
read -r -d '' HELP << EOF
usage: install [-h]

Install dotfiles

Symlinks are created *forcefully*, so existing files and directories in any of
the target paths will be irrevocably destroyed without mercy. Read this script
before running it!

optional arguments:
  -h, --help  show this help message and exit

EOF
[[ $1 == '-h' || $1 == '--help' ]] && { echo "$HELP"; exit 0; }


read -r -d '' WRONG_DIRECTORY_ERROR << EOF
Error: this scirpt must be run from the dotfiles directory, "$HOME/.dotfiles"
EOF
[[ $PWD != $HOME/.dotfiles ]] && { echo "$WRONG_DIRECTORY_ERROR"; exit 1; }


function symlink {
    [[ -L $2 || -e $2 ]] && rm -rf "$2"
    ln -s "$1" "$2"
}


symlink $PWD/bash_profile $HOME/.bash_profile
symlink $PWD/bashrc $HOME/.bashrc

mkdir -m 700 -p $HOME/.config

symlink $PWD/git $HOME/.config/git

symlink $PWD/nvim $HOME/.config/nvim

mkdir -m 700 -p $HOME/.ssh
symlink $PWD/ssh/config $HOME/.ssh/config

mkdir -p $HOME/.ipython/profile_default
symlink $PWD/ipython_config.py $HOME/.ipython/profile_default/ipython_config.py

symlink $PWD/ghci $HOME/.ghci
symlink $PWD/haskeline $HOME/.haskeline
