#!/usr/bin/env bash

read -r -d '' help_message <<EOF
Install macos dotfiles. Assumes the base installation from
\`github.com/jesaerys/dotfiles\` is already in place.

usage: install [-fh]

options:
 -f          force create links, overwriting all targets that already exist
 -h, --help  show this help message and exit
EOF

[[ $PWD == ${PWD%/dotfiles/macos} ]] && echo "\
It looks like you aren't in the \`dotfiles/macos\` directory.
Please navigate to \`dotfiles/macos\` and try ./install again."\
&& exit 1

f=''

while :; do
    case $1 in
        -h|--help) echo "$help_message"; exit 0;;
        -f) f='f';;
        *) break
    esac
    shift
done

mkdir -p "${HOME}/.config/dotfiles/bash/pre"
mkdir -p "${HOME}/.config/dotfiles/bash/post"
ln -shi"$f" "${PWD}/bash/pre" "${HOME}/.config/dotfiles/bash/pre/macos"
ln -shi"$f" "${PWD}/bash/post" "${HOME}/.config/dotfiles/bash/post/macos"

orig_umask="$(umask)"
umask 0077
mkdir -p "${HOME}/.ssh"
umask "$orig_umask"

ln -si"$f" "${PWD}/ssh/config" "${HOME}/.ssh/config"

mkdir -p "${HOME}/.hammerspoon"
ln -si"$f" "${PWD}/hammerspoon/init.lua" "${HOME}/.hammerspoon/init.lua"

mkdir -p "${HOME}/.config/nvim"
ln -si"$f" "${PWD}/nvim/init.vim" "${HOME}/.config/nvim/init.vim"
mkdir -p "${HOME}/.config/nvim/colors"
ln -si"$f" "$(cd ..; echo $PWD)/vim/base16-default-light.vim" "${HOME}/.config/nvim/colors/base16-default-light.vim"

ln -shi"$f" "/usr/local/opt/ncurses/share/terminfo" "${HOME}/.terminfo"

ln -si"$f" "${PWD}/conda/condarc" "${HOME}/.condarc"

unset f
