# Extension mechanism for extra completions
fpath=(~/.local/share/zsh/site-functions $fpath)

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' format '%d:'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' menu select=1
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' verbose true

autoload -Uz compinit
compinit

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

setopt extendedglob
setopt interactivecomments
setopt sharehistory
unsetopt beep
unsetopt flowcontrol  # Prevent terminal driver from ^S/^Q; see stty

bindkey -v
bindkey -v '^F' forward-char
bindkey -v '^B' backward-char
bindkey -v '^E' end-of-line
bindkey -v '^A' beginning-of-line
bindkey -v '^N' down-line-or-history
bindkey -v '^P' up-line-or-history
bindkey -v '^?' backward-delete-char
bindkey -v '^K' kill-line
bindkey -v '^R' history-incremental-search-backward
bindkey -v '^S' history-incremental-search-forward
export KEYTIMEOUT=1  # Faster escape into command mode

# Redefine up/down history commands to only look locally
down-line-or-history() {
    zle set-local-history 1
    zle .down-line-or-history
    zle set-local-history 0
}
zle -N down-line-or-history
up-line-or-history() {
    zle set-local-history 1
    zle .up-line-or-history
    zle set-local-history 0
}
zle -N up-line-or-history

# Navigate completion menu with ctrl-n/p
bindkey '^N' expand-or-complete
bindkey '^P' reverse-menu-complete

PS1='%B%F{4}%1~ ❯ %f%b'

unalias run-help  # run-help is the default alias for man
autoload run-help
alias help='run-help'

alias ls='ls -F'
alias ll='ls -l'

PATH="$HOME/.local/bin:$PATH"

# Extension mechanism for extra shell configs
for zshrc in ~/.config/zsh/zshrc.d/*(N); do
    source "$zshrc"
done

