[[ -f "${HOME}/.config/dotfiles/pre" ]] && source "${HOME}/.config/dotfiles/pre"

shopt -s \
    dotglob \
    extglob

PATH="${HOME}/.local/bin:${PATH}"

export PS1='\[\e[1m\]\W ❯ \[\e[0m\]'
export EDITOR=vi


source "${HOME}/.dotfiles/ls/init"
source "${HOME}/.dotfiles/grep/init"
source "${HOME}/.dotfiles/direnv/init"
source "${HOME}/.dotfiles/cargo/init"
source "${HOME}/.dotfiles/vscode/init"

[[ -f "${HOME}/.config/dotfiles/post" ]] && source "${HOME}/.config/dotfiles/post"
