" A minimal vimrc based on sensible.vim.
" Useful for linux servers and stock macOS.

source $DOTFILES/vim/sensible.vim

set background=light
set expandtab
set shiftwidth=4
set hlsearch
set incsearch
set wrapscan
set number
set showcmd
set showmode
set completeopt=menu,menuone,preview,longest
